name: 'Release Base Action'
description: 'Github Composite Action for modix base releases'
inputs:
  image:
    description: 'Name for the image'
    required: true
  tag:
    description: 'Tag for the image'
    required: true
  dir:
    description: 'Directory with the Dockerfile and docker context folder to build'
    required: true
  github-token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Repository owner'
    required: true
    default: ${{ github.repository_owner }}
  repository:
    description: 'Github repository'
    required: true
    default: ${{ github.repository }}
  sha:
    description: 'Github SHA'
    required: true
    default: ${{ github.sha }}
  customer-id:
    description: 'AWS Customer ID'
    required: true
    default: '245309753215'
  region:
    description: 'AWS Region'
    required: true
    default: 'eu-central-1'
  aws-key:
    description: 'AWS Key'
    required: true
  aws-secret:
    description: 'AWS Secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Dockerfile
      uses: zolex/include-action@v2
      id: dockerfile
      with:
        input: ${{ inputs.dir }}/Dockerfile
        output: ${{ inputs.dir }}/Dockerfile.out

    - uses: LouisBrunner/checks-action@v1.2.0
      with:
        token: ${{ inputs.github-token }}
        repo: ${{ inputs.repository }}
        sha: ${{ inputs.sha }}
        name: ${{ inputs.image }}:${{ inputs.tag }} Dockerfile
        status: completed
        conclusion: ${{ steps.dockerfile.outputs.conclusion }}
        output: |
          {"summary": "Dockerfile build status: ${{ steps.dockerfile.outputs.conclusion }}"}
        output_text_description_file: ${{ steps.dockerfile.outputs.dockerfile }}

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ${{ inputs.dir }}/Dockerfile.out

    - name: Ensure context
      shell: sh
      run:  mkdir -p ${{ inputs.dir }}/docker

    - name: Set Image Tag
      shell: sh
      run: |
        echo "IMAGE_TAG=${{ inputs.customer-id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/modix/base/${{ inputs.image }}:${{ inputs.tag }}" >> $GITHUB_ENV

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.dir }}/docker
        file: ${{ inputs.dir }}/Dockerfile.out
        push: false
        outputs: type=docker
        tags: ${{ env.IMAGE_TAG }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-key }}
        aws-secret-access-key: ${{ inputs.aws-secret }}
        aws-region: ${{ inputs.region }}

    - name: Login to Amazon ECR (prod_eu)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to AWS ECR (prod_eu)
      shell: sh
      run: |
        docker push ${{ env.IMAGE_TAG }}

    - uses: LouisBrunner/checks-action@v1.2.0
      with:
        token: ${{ inputs.github-token }}
        repo: ${{ inputs.repository }}
        sha: ${{ inputs.sha }}
        name: ${{ inputs.image }}:${{ inputs.tag }} Image
        status: completed
        conclusion: ${{ job.status }}
        output: |
          {
            "summary": "Build status: ${{ job.status }}",
            "text_description": "Image pushed to [${{ env.IMAGE_TAG }}](https://${{ inputs.region }}.console.aws.amazon.com/ecr/repositories/private/${{ inputs.customer-id }}/modix/base/${{ inputs.image }})"
          }

#    - id: vars
#      shell: sh
#      run: |
#        echo ::set-output name=owner::$(echo "${{ inputs.repository }}" | awk -F / '{print $1}')
#        echo ::set-output name=repo::$(echo "${{ inputs.repository }}" | awk -F / '{print $2}')
#
#    - uses: actions/github-script@v4
#      with:
#        github-token: ${{ inputs.github-token }}
#        debug: true
#        script: |
#          const date = new Date();
#          const check = await github.checks.create({
#            owner: "${{ steps.vars.outputs.owner }}",
#            repo: "${{ steps.vars.outputs.repo }}",
#            name: "Custom Script ${{ github.run_id }}",
#            started_at: date.toISOString(),
#            completed_at: date.toISOString(),
#            head_sha: "${{ inputs.sha }}",
#            external_id: "${{ github.run_id }}",
#            status: "completed",
#            conclusion: "success",
#            output: {
#              title: "Some funny title",
#              summary: "Build status: ${{ job.status }}",
#              text: "Image pushed to [${{ env.IMAGE_TAG }}](https://${{ inputs.region }}.console.aws.amazon.com/ecr/repositories/private/${{ inputs.customer-id }}/modix/base/${{ inputs.image }})"
#            }
#          });