name: 'Release Base Action'
description: 'Github Composite Action for modix base releases'
inputs:
  image:
    description: 'Name and Tag of the image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile to build'
    required: true
  context:
    description: 'Context for buildx'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Dockerfile
      uses: zolex/include-action@v1
      with:
        input: ${{ inputs.dockerfile }}
        output: ${{ inputs.dockerfile }}.out

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ${{ inputs.dockerfile }}.out

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}.out
        push: false
        tags: 245309753215.dkr.ecr.eu-central-1.amazonaws.com/modix/base/${{ inputs.image }}
