name: 'Release Base Action'
description: 'Github Composite Action for modix base releases'
inputs:
  image:
    description: 'Name for the image'
    required: true
  tag:
    description: 'Tag for the image'
    required: true
  dir:
    description: 'Directory with the Dockerfile and docker context folder to build'
    required: true
  github-token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Repository owner'
    required: true
    default: ${{ github.repository_owner }}
  repository:
    description: 'Github repository'
    required: true
    default: ${{ github.repository }}
  sha:
    description: 'Github SHA'
    required: true
    default: ${{ github.sha }}
  customer-id:
    description: 'AWS Customer ID'
    required: true
    default: '245309753215'
  region:
    description: 'AWS Region'
    required: true
    default: 'eu-central-1'
  aws-key:
    description: 'AWS Key'
    required: true
  aws-secret:
    description: 'AWS Secret'
    required: true

runs:
  using: 'composite'
  steps:
    - id: vars
      shell: sh
      run: |
        echo ::set-output name=owner::$(echo "${{ inputs.repository }}" | awk -F / '{print $1}')
        echo ::set-output name=repo::$(echo "${{ inputs.repository }}" | awk -F / '{print $2}')

    - uses: actions/github-script@v4
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const date = new Date();
          const check = await github.checks.create({
            owner: "${{ steps.vars.outputs.owner }}",
            repo: "${{ steps.vars.outputs.repo }}",
            name: "Custom Script",
            started_at: date.toISOString(),
            completed_at: date.toISOString(),
            head_sha: "${{ inputs.sha }}",
            external_id: "${{ github.run_id }}",
            status: "completed",
            conclusion: "success",
            output: {
              title: "Some funny title",
              summary: "Build status: ${{ job.status }}",
              text: "Image pushed to [${{ env.IMAGE_TAG }}](https://${{ inputs.region }}.console.aws.amazon.com/ecr/repositories/private/${{ inputs.customer-id }}/modix/base/${{ inputs.image }})"
            }
          });
