name: 'Release Base Action'
description: 'Github Composite Action for modix base releases'
inputs:
  image:
    description: 'Name and Tag of the image'
    required: true
  dir:
    description: 'Directory with the Dockerfile and docker context folder to build'
    required: true
  github-token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Repository owner'
    required: true
    default: ${{ github.repository_owner }}
  repository:
    description: 'Github repository'
    required: true
    default: ${{ github.repository }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1



    - uses: octokit/request-action@v2.1.0
      id: build_dockerfile
      with:
        route: POST /repos/{owner}/{repo}/check-runs
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repository }}
        name: "Build Dockerfile"
        head_sha: ${{ github.sha }}
        output: |
          title: Build Dockerfile
          summary: A summary of the test check run
          images:
            - alt: Test image
              image_url: https://octodex.github.com/images/jetpacktocat.png
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Build Dockerfile
      uses: zolex/include-action@v1
      with:
        input: ${{ inputs.dir }}/Dockerfile
        output: ${{ inputs.dir }}/Dockerfile.out

    - uses: octokit/request-action@v2.1.0
      with:
        route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repository }}
        check_run_id: ${{ fromJson(steps.build_dockerfile.outputs.data).id }}
        conclusion: "success"
        status: "completed"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}



    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ${{ inputs.dir }}/Dockerfile.out

    - name: Ensure context
      shell: sh
      run:  mkdir -p ${{ inputs.dir }}/docker

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.dir }}/docker
        file: ${{ inputs.dir }}/Dockerfile.out
        push: false
        tags: |
          modix/base/${{ inputs.image }}
          245309753215.dkr.ecr.eu-central-1.amazonaws.com/modix/base/${{ inputs.image }}

    - name: Scan Image
      uses: azure/container-scan@v0
      with:
        image-name: modix/base/${{ inputs.image }}
