name: 'Release Base Action'
description: 'Github Composite Action for modix base releases'
inputs:
  image:
    description: 'Name and Tag of the image'
    required: true
  dir:
    description: 'Directory with the Dockerfile and docker context folder to build'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Dockerfile
      uses: zolex/include-action@v1
      with:
        input: ${{ inputs.dir }}/Dockerfile
        output: ${{ inputs.dir }}/Dockerfile.out

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ${{ inputs.dir }}/Dockerfile.out

    - name: Ensure context
      shell: sh
      run:  mkdir -p ${{ inputs.dir }}/docker

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.dir }}/docker
        file: ${{ inputs.dir }}/Dockerfile.out
        push: false
        tags: 245309753215.dkr.ecr.eu-central-1.amazonaws.com/modix/base/${{ inputs.image }}
